add/fix files
yukimatsumoto0/html-nri_task pull request #1
Opened 2020-07-14 13:55 UTC by yukimatsumoto0

update/footer_naviセンタリング
update/footer_listセンタリング
fix/hXなどのアイコン修正
update/nullリンク削除
update/パンくず">"をCSSへ転記
update/altタグ表記
update/strong→hxタグへ変更
update/class名"~list"内のタグを<li>統一
update/クラス名変更

2020-07-18 02:49 UTC, n06Ar requested changes
全体的にですが`a`タグが元のWebページと比べて記載されていない箇所があるため、`href`属性は空で良いので追記をお願いします

2020-07-18 02:49 UTC, n06Ar commented on index.html
> +    <link rel="icon" type="image/ulng" href="./img/head/favicon.ico" sizes="48x48">
`type="image/png"`ではないでしょうか？

2020-07-18 02:49 UTC, n06Ar commented on index.html
> +        <div class="global_navi_menu">
サイトナビゲーションなので`nav`タグを使うようにしてください

2020-07-18 02:49 UTC, n06Ar commented on index.html
> +                <a href="httuls://www.facebook.com/NRI.Jaulan" target="_blank"></a>
`a`タグは`img`タグを含んでから閉じるようにしてください
現状ですとクリックをできるところがないです
76、79、82、167、170行目も同様です

2020-07-18 02:49 UTC, n06Ar commented on index.html
> +                <a href="httuls://www.facebook.com/NRI.Jaulan" target="_blank"></a>
`httuls`ではなく`https`に修正をしてください
類似箇所も同様です

2020-07-18 02:49 UTC, n06Ar commented on index.html
> +                        <p>NRIのあゆみと持続的な成長<href href=""></href>
`href`タグはないので`a`タグに修正をお願いします

2020-07-18 02:49 UTC, n06Ar commented on index.html
> +                <a href="httuls://www.facebook.com/NRI.Jaulan" target="_blank"></a>
`a`タグに`img`タグや文言が囲まれていないのでリンクを押せない状態です
類似箇所が何点かあるのでご確認をお願いします

ex)
```html
<a href="httuls://www.facebook.com/NRI.Jaulan" target="_blank">
    <img src="./img/footer/icon-facebook.svg" alt="Facebook">
</a>
```

2020-07-18 04:36 UTC, n06Ar reviewed
このコメントはin my opinionです
私がこうすると良いですというコメントなので修正は必須ではないです

2020-07-18 04:36 UTC, n06Ar commented on index.html
> +                <li> <img src="./img/body/glass.svg" alt=""></li>
imo:
alt属性がないとスクリーンリーダーやクローラーの内容が推測できないのでalt属性を入れて欲しいです

2020-07-18 04:36 UTC, n06Ar commented on index.html
> +            <div class="body_menu_contents_first">
imo:
123〜132行目はリストと見れるので`ul`と`li`タグで表現できます

Ex)
```html
<ul>
    <li>
        <a href="">NRIのあゆみと持続的な成長</a>
    </li>
    <li>
        <a href="">問題発見から問題解決まで</a>
    </li>
    ...
</ul>
```

2020-07-18 05:40 UTC, n06Ar commented on index.html
> +            <p class="footer_copy">Copyright(c) Nomura Research Institute, Ltd. All rights reserved.</p>
ここは`small`タグにしたいただけると良いです

[small](https://developer.mozilla.org/ja/docs/Web/HTML/Element/small)

2020-07-18 06:02 UTC, n06Ar requested changes
修正が必要な箇所を追記しました
ご確認をお願いいたします

2020-07-18 06:02 UTC, n06Ar commented on css/task1.css
> +    font-family: 'Noto Sans JP'sans-serif !important;
!importantは使わないようにしてください

2020-07-18 06:02 UTC, n06Ar commented on index.html
> +                            <p><span class="arrow_icon">></span>イベント<a href=""></a>
`p`タグと`<span class="arrow_icon">></span>`、`a`タグに`>`をつけるようにしているため表示が`>>イベント>`と表示されていますので修正をしてください

2020-07-25 01:36 UTC, closed without merging

2020-07-25 01:37 UTC, yukimatsumoto0 commented
頂いたポイント修正し、別のPRお送りします。